# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('book_name', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=500)),
                ('cover', models.ImageField(upload_to=b'')),
                ('sample', models.FileField(default=None, upload_to=b'')),
                ('author', models.CharField(max_length=30)),
                ('added_on', models.DateField(auto_now=True)),
                ('published_on', models.DateField(default=None)),
                ('publisher', models.CharField(default='Not Provided', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30)),
                ('genre_logo', models.ImageField(default='no_image.jpg', upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_reader', models.CharField(default=None, max_length=100)),
                ('dob', models.DateField(default=None)),
                ('country', models.CharField(default=None, max_length=30)),
                ('reader_profile_picture', models.FileField(default=None, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_read_on', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Reader')),
            ],
        ),
        migrations.CreateModel(
            name='Text_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('posting_time', models.TimeField()),
                ('posting_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Reader')),
            ],
        ),
        migrations.CreateModel(
            name='Video_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=b'')),
                ('youtube_link', models.TextField()),
                ('rating', models.FloatField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.Reader')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='books_read',
            field=models.ManyToManyField(default=None, through='readers.ReadingDetails', to='readers.Book'),
        ),
        migrations.AddField(
            model_name='reader',
            name='favourite_genre',
            field=models.ManyToManyField(default=None, to='readers.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='readers.Genre'),
        ),
    ]
