# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('synopsis', models.TextField(max_length=500)),
                ('cover', models.ImageField(upload_to=b'')),
                ('sample', models.FileField(default=None, upload_to=b'')),
                ('author', models.CharField(max_length=30)),
                ('added_on', models.DateField(auto_now=True)),
                ('published_on', models.DateField(default=None)),
                ('publisher', models.CharField(default='Not Provided', max_length=30)),
                ('genre', models.ManyToManyField(to='readers.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_read',
            field=models.ManyToManyField(default=None, through='readers.ReadingDetails', to='readers.MyBook'),
        ),
        migrations.AlterField(
            model_name='readingdetails',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.MyBook'),
        ),
        migrations.AlterField(
            model_name='text_review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.MyBook'),
        ),
        migrations.AlterField(
            model_name='video_review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readers.MyBook'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
