# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0009_text_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_review',
            name='user',
        ),
    ]
