# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0010_remove_text_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='about_reader',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='books_read',
            field=models.ManyToManyField(blank=True, through='readers.ReadingDetails', to='readers.MyBook'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reader',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='favourite_genre',
            field=models.ManyToManyField(blank=True, to='readers.Genre'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_profile_picture',
            field=models.FileField(default='no_image.png', upload_to=b''),
        ),
    ]
