# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0012_auto_20170410_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text_review',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(6.0)]),
        ),
    ]
